--[[ Credit for these translations goes to:
	Mordroba
	Djidiouf
	Fenrirpims
	Ikshaar
	Avold
	Viny
	contrebasse
--]]
local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "frFR", false)
if not L then return end










L["ALPHAPANEL_TITLE"] = "Transparence"
L["BleedDamageTaken"] = "Dégâts de saignement subis augmentés"
L["Bleeding"] = "Saigne"
L["BonusAgiStr"] = "Agilité/Force augmentée"
L["BonusArmor"] = "Armure augmentée"
L["BonusMana"] = "Réserve de Mana augmentée"
L["BonusStamina"] = "Endurance augmentée"
L["BurstHaste"] = "Burst de hâte"
L["BurstManaRegen"] = "Burst de Regen Mana"
L["CASTERFORM"] = "Forme de lanceur de sorts"
L["CHOOSENAME_DIALOG"] = [=[Entrer le nom ou l'id du Sort/Capacité/Objet/Buff/Débuff attribué à cette icône. Vous pouvez ajouter de multiples buffs/débuffs en les séparant avec ';'.
COMPETENCES PET devraient utiliser SpellIDs.]=] -- Needs review
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "Ensembles de sorts prédéfinis."
L["CHOOSENAME_EQUIVS_TOOLTIP"] = "Vous pouvez sélectionner un ensemble prédéfini de buffs/debuffs dans ce menu."
L["CMD_OPTIONS"] = "Options"
L["CONDITIONPANEL_ALIVE"] = "Unité est en vie" -- Needs review
L["CONDITIONPANEL_ALIVE_DESC"] = "Le test passera si l'unité est en vie" -- Needs review
L["CONDITIONPANEL_AND"] = "Et"
L["CONDITIONPANEL_ANDOR"] = "Et / Ou"
L["CONDITIONPANEL_COMBAT"] = "Unité est en combat"
L["CONDITIONPANEL_COMBO"] = "Points de combo"
L["CONDITIONPANEL_ECLIPSE_DESC"] = [=[Eclipse fonctionne sur une fourchette de valeurs allant de -100 (éclipse lunaire) à 100 (éclipse solaire).
Entrez -80 si vous voulez faire fonctionner l'icône avec une valeur de 80 en éclipse lunaire.]=]
L["CONDITIONPANEL_EQUALS"] = "Égal à"
L["CONDITIONPANEL_EXISTS"] = "L'unité existe"
L["CONDITIONPANEL_GREATER"] = "Plus Grand Que"
L["CONDITIONPANEL_GREATEREQUAL"] = "Plus Grand Que ou Égal à"
L["CONDITIONPANEL_ICON"] = "Icône affichée"
L["CONDITIONPANEL_ICON_DESC"] = [=[La condition sera remplie si l'icône spécifiée est actuellement affichée avec une transparence supérieure à 0%.
Si vous ne voulez pas afficher les icônes cochées, cochez l'option "Faussement caché" dans les réglages de la transparence de l'icône.
Le groupe de l'icône cochée doit aussi être affiché pour cocher l'icône.]=]
L["CONDITIONPANEL_LESS"] = "Moins Que"
L["CONDITIONPANEL_LESSEQUAL"] = "Moins Que ou Égal à"
L["CONDITIONPANEL_NOTEQUAL"] = "Pas Égal à"
L["CONDITIONPANEL_OPERATOR"] = "Opérateur"
L["CONDITIONPANEL_OR"] = "Ou"
L["CONDITIONPANEL_POWER"] = "Puissance"
L["CONDITIONPANEL_POWER_DESC"] = [=[Vérifiera l'énergie du personnage s'il s'agit d'un druide en forme de félin,
sa rage si le personnage est un guerrier, etc.]=]
L["CONDITIONPANEL_PVPFLAG"] = "Unité est taggué PVP"
L["CONDITIONPANEL_TITLE"] = "Éditeur de condition TellMeWhen"
L["CONDITIONPANEL_TYPE"] = "Type"
L["CONDITIONPANEL_UNIT"] = "Personnage"
L["CONDITIONPANEL_VALUE"] = "Pourcent"
L["CONDITIONPANEL_VALUEN"] = "Valeur"
L["COPY"] = "Copier"
L["COPYICON"] = "Icône"
L["COPYPANEL_GROUP"] = "Groupe :"
L["COPYPANEL_ICON"] = "Icône :"
L["COPYPOS"] = "Copier position/échelle"
L["DISABLED"] = "Désactivé"
L["DURATIONPANEL_TITLE"] = "Durée"
L["Disarmed"] = "Désarmé"
L["Disoriented"] = "Désorienté"
L["ECLIPSE_DIRECTION"] = "Sens de l'éclipse"
L["ENABLED"] = "Activé"
L["FALSE"] = "Faux"
L["FROM"] = "De :"
L["Feared"] = "Peur"
L["GROUP"] = "Groupe"
L["GROUPICON"] = "Groupe : %s, Icône : %d"
L["HPSSWARN"] = "Attention ! Toute condition que vous avez cochée concernant la puissance sacrée ou les fragments d'âme risquent d'être buggée ! Cochez-les pour empêcher de futures confusions !"
L["ICONALPHAPANEL_FAKEHIDDEN"] = "Faussement cachée"
L["ICONALPHAPANEL_FAKEHIDDEN_DESC"] = "Tout le temps cacher l’icône tout en la laissant active afin de permettre aux conditions des autres icônes d'effectuer des vérifications sur l’icône faussement cachée."
L["ICONMENU_ABSENT"] = "Absent"
L["ICONMENU_ALPHA"] = "Transparence"
L["ICONMENU_ALWAYS"] = "Toujours"
L["ICONMENU_BARS"] = "Barres"
L["ICONMENU_BOTH"] = "Soit"
L["ICONMENU_BUFF"] = "Buff"
L["ICONMENU_BUFFDEBUFF"] = "Buff/Débuff"
L["ICONMENU_BUFFTYPE"] = "Buff ou débuff ?"
L["ICONMENU_CASTSHOWWHEN"] = "Montrer quand un sort est"
L["ICONMENU_CHOOSENAME"] = "Choisir sort/objet/buff/etc."
L["ICONMENU_CLEAR"] = "Effacer les réglages"
L["ICONMENU_COOLDOWN"] = "Cooldown"
L["ICONMENU_COOLDOWNCHECK"] = "Vérification de cooldown ?"
L["ICONMENU_COOLDOWNTYPE"] = "Type de cooldown"
L["ICONMENU_DEBUFF"] = "Débuff"
L["ICONMENU_DURATION_MAX_DESC"] = "Durée maximale permise pour afficher l'icône"
L["ICONMENU_DURATION_MIN_DESC"] = "Durée minimale nécessaire pour afficher l'icône"
L["ICONMENU_EDIT"] = "Éditer"
L["ICONMENU_EITHER"] = "Toutes les unités"
L["ICONMENU_ENABLE"] = "Activer l'icône"
L["ICONMENU_FOCUSTARGET"] = "Cible du focus"
L["ICONMENU_FRIEND"] = "Unités amicales"
L["ICONMENU_HIDEUNEQUIPPED"] = "Cacher quand le trou est vide"
L["ICONMENU_HOSTILE"] = "Unités hostiles"
L["ICONMENU_INVERTBARS"] = "Inverser les barres"
L["ICONMENU_ITEM"] = "Objet"
L["ICONMENU_MANACHECK"] = "Vérification de la quantité de puissance ?" -- Needs review
L["ICONMENU_MOUSEOVER"] = "Survol de la souris"
L["ICONMENU_MOUSEOVERTARGET"] = "Cible du survol de la souris"
L["ICONMENU_ONLYMINE"] = "Ne montrer que si lancé par soi"
L["ICONMENU_PETTARGET"] = "Cible du familier"
L["ICONMENU_PRESENT"] = "Présent"
L["ICONMENU_RANGECHECK"] = "Vérification de la portée ?"
L["ICONMENU_REACT"] = "Réaction d'unités"
L["ICONMENU_REACTIVE"] = "Sort réactif ou capacité"
L["ICONMENU_SHOWCBAR"] = "Montrer barre cooldown/timer"
L["ICONMENU_SHOWPBAR"] = "Montrer barre de puissance"
L["ICONMENU_SHOWTIMER"] = "Montrer le timer"
L["ICONMENU_SHOWTIMERTEXT"] = "Afficher le numéro du timer"
L["ICONMENU_SHOWTIMERTEXT_DESC"] = "Ne peut être appliquer que si \"Montrer le timer\" est coché"
L["ICONMENU_SHOWWHEN"] = "Montrer l'icône quand"
L["ICONMENU_SPELL"] = "Sort ou capacité"
L["ICONMENU_STACKS_MAX_DESC"] = "Nombre maximum de stacks de l'aura requis pour montrer l'icône"
L["ICONMENU_STACKS_MIN_DESC"] = "Nombre minimum de stacks de l'aura requis pour montrer l’icône"
L["ICONMENU_TARGETTARGET"] = "Cible de la cible"
L["ICONMENU_TOTEM"] = "Totem/Goule non améliorée"
L["ICONMENU_TYPE"] = "Type d'icône"
L["ICONMENU_UNUSABLE"] = "Inutilisable"
L["ICONMENU_USABLE"] = "Utilisable"
L["ICONMENU_VEHICLE"] = "Véhicule"
L["ICONMENU_WPNENCHANT"] = "Enchantement d'arme temporaire"
L["ICONMENU_WPNENCHANTTYPE"] = "Slot d'arme à surveiller"
L["ICONTOCHECK"] = "Icône à vérifier"
L["ICON_TOOLTIP1"] = "TellMeWhen"
L["ImmuneToMagicCC"] = "Immunisé aux contrôles magiques"
L["ImmuneToStun"] = "Immunisé aux étourdissements"
L["Incapacitated"] = "Incapacité"
L["IncreasedAP"] = "Puissance d'Attaque augmentée"
L["IncreasedCrit"] = "Chance de Coup Critique augmentée"
L["IncreasedDamage"] = "Dégâts Infligés augmentés"
L["IncreasedPhysHaste"] = "Hâte en mêlée augmentée"
L["IncreasedSPsix"] = "Puissance des sorts augmentée (6%)"
L["IncreasedSPten"] = "Puissance des sorts augmentée (10%)"
L["IncreasedSpellHaste"] = "Hâte des sorts augmentée"
L["IncreasedStats"] = "Stats augmentées"
L["LDB_TOOLTIP1"] = "|cff7fffffCliquer-gauche|r pour basculer le verrouillage des groupes" -- Needs review
L["LDB_TOOLTIP2"] = "Cliquer-droit pour montrer/cacher certains groupes "
L["MOON"] = "Lunaire"
L["Magic"] = "Magie"
L["ManaRegen"] = "Régen Mana augmentée"
L["NONE"] = "Aucune des valeurs ci-dessous"
L["PhysicalDmgTaken"] = "Dégâts Physiques subits augmentés"
L["Poison"] = "Poison"
L["PushbackResistance"] = "Résistance au retard des sorts augmentée"
L["RESIZE"] = "Redimensionner"
L["RESIZE_TOOLTIP"] = "Cliquer et glisser pour changer la taille"
L["ReducedArmor"] = "Armure réduite"
L["ReducedAttackSpeed"] = "Vitesse d'attaque réduite"
L["ReducedCastingSpeed"] = "Vitesse d'incantation réduite"
L["ReducedHealing"] = "Soins prodigués réduits"
L["ReducedPhysicalDone"] = "Dommages physiques infligés réduits"
L["Resistances"] = "Résistance aux sorts augmentée"
L["Rooted"] = "Immobilisé"
L["STACKSPANEL_TITLE"] = "Stacks"
L["SUN"] = "Solaire"
L["Silenced"] = "Silence"
L["SpellCritTaken"] = "Chance de coup critique augmentée"
L["SpellDamageTaken"] = "Augmentation des dégâts des sorts subis"
L["Stunned"] = "Étourdi"
L["TO"] = "À :"
L["TRUE"] = "Vrai"
L["UIPANEL_ADDGROUP"] = "Ajouter un autre groupe"
L["UIPANEL_ALLRESET"] = "Réinitialiser toutes les icônes"
L["UIPANEL_BARIGNOREGCD"] = "Les barres ignorent le GCD"
L["UIPANEL_BARIGNOREGCD_DESC"] = "Si cochée, les barres des cooldowns ne changeront pas de valeur si le cooldown déclenché est un cooldown global"
L["UIPANEL_BARTEXTURE"] = "Texture de barre"
L["UIPANEL_CLOCKIGNOREGCD"] = "Les timers ignorent le GCD"
L["UIPANEL_CLOCKIGNOREGCD_DESC"] = "Si cochée, les timers et l'horloge à cooldown ne se déclencheront pas à partir d'un cooldown global"
L["UIPANEL_COLOR"] = "Couleur de la barre de cooldown/durée"
L["UIPANEL_COLORS"] = "Couleurs"
L["UIPANEL_COLOR_ABSENT"] = "Couleur d'absence"
L["UIPANEL_COLOR_ABSENT_DESC"] = "Teinte de l'icône quand elle est réglée sur toujours afficher et que le buff/debuff/enchantement/totem est absent."
L["UIPANEL_COLOR_COMPLETE"] = "Cooldown/Durée terminée"
L["UIPANEL_COLOR_COMPLETE_DESC"] = "Couleur de la barre de fondu de cooldown/durée quand le cooldown/la durée viens de commencer"
L["UIPANEL_COLOR_DESC"] = "Les options suivantes n'affectent que les couleurs des icônes réglées sur\"afficher tout le temps"
L["UIPANEL_COLOR_OOM"] = "Barre de puissance vide : couleur" -- Needs review
L["UIPANEL_COLOR_OOM_DESC"] = "Teinte et transparence de l'icône quand vous manquez de mana/rage/énergie/focalisation/puissance runique pour lancer le sort"
L["UIPANEL_COLOR_OOR"] = "Couleur : hors de portée"
L["UIPANEL_COLOR_OOR_DESC"] = "Teinte et transparence de l'icône quand vous n'êtes pas à portée de la cible pour lancer le sort"
L["UIPANEL_COLOR_PRESENT"] = "Couleur de présence"
L["UIPANEL_COLOR_PRESENT_DESC"] = "Teinte de l'icône quand elle est réglée sur \"toujours afficher\" et que le buff/debuff/enchantement/totem est présent."
L["UIPANEL_COLOR_STARTED"] = "Commencement du cooldown/de la durée"
L["UIPANEL_COLOR_STARTED_DESC"] = "Couleur de la barre de fondu de cooldown/durée quand le cooldown/la durée vient de commencer"
L["UIPANEL_COLUMNS"] = "Colonnes"
L["UIPANEL_DELGROUP"] = "Supprimer ce Groupe"
L["UIPANEL_DRAWEDGE"] = "Surbrillance de la bordure du timer"
L["UIPANEL_DRAWEDGE_DESC"] = "Mets en surbrillance la bordure du timer de cooldown (animation en forme de montre) pour augmenter sa visibilité"
L["UIPANEL_ENABLEGROUP"] = "Activer Groupe"
L["UIPANEL_FONT"] = "Texte des stacks"
L["UIPANEL_FONT_DESC"] = "Choisissez la police d'écriture à utiliser pour le texte des stacks des icônes."
L["UIPANEL_FONT_SIZE"] = "Taille de la police"
L["UIPANEL_GROUPRESET"] = "Réinitialiser Position"
L["UIPANEL_GROUPS"] = "Groupes"
L["UIPANEL_ICONGROUP"] = "Groupe d'icône "
L["UIPANEL_ICONSPACING"] = "Espacement des icônes" -- Needs review
L["UIPANEL_ICONSPACING_DESC"] = "Espace entre les icones du même groupe" -- Needs review
L["UIPANEL_LOCK"] = "Verrouiller l'AddOn"
L["UIPANEL_LOCKUNLOCK"] = "Verrouiller/Déverrouiller l'AddOn"
L["UIPANEL_MAINOPT"] = "Options générales"
L["UIPANEL_NOCOUNT"] = "Afficher le texte des timers"
L["UIPANEL_NOCOUNT_DESC"] = "Active/désactive le texte qui affiche le cooldown sur l'icone. Il ne s'affichera que si le timer de l'icone est actif, que cette option est activée et QUE L'ADD-ON OMNICC EST INSTALLE"
L["UIPANEL_NOTINVEHICLE"] = "Cacher en véhicule"
L["UIPANEL_ONLYINCOMBAT"] = "Ne montrer qu'en combat"
L["UIPANEL_PRIMARYSPEC"] = "Spé principale"
L["UIPANEL_ROWS"] = "Lignes"
L["UIPANEL_SECONDARYSPEC"] = "Spé secondaire"
L["UIPANEL_STANCE"] = "Afficher quand :"
L["UIPANEL_SUBTEXT2"] = "Les icônes fonctionnent lorsqu'elles sont verrouillées. Si déverrouillées, vous pouvez déplacer/redimensionner les groupes d'icônes et cliquer droit les icônes individuelles pour plus de réglages. Vous pouvez aussi taper '/tellmewhen' ou '/tmw' pour verrouiller/déverrouiller."
L["UIPANEL_TOOLTIP_ALLRESET"] = "Réinitialiser les DONNÉES et la POSITION de toutes les icônes"
L["UIPANEL_TOOLTIP_COLUMNS"] = "Nombre de colonnes d'icônes pour ce groupe"
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "Montrer et activer ce groupe d'icônes"
L["UIPANEL_TOOLTIP_GROUPRESET"] = "Réinitialise la position de ce groupe"
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "Cocher pour ne montrer ce groupe d'icônes qu'en combat"
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "Cocher pour montrer ce groupe d'icônes alors que votre spé principale est active"
L["UIPANEL_TOOLTIP_ROWS"] = "Nombre de lignes d'icônes pour ce groupe"
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "Cocher pour montrer ce groupe d'icônes alors que votre spé secondaire est active"
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "Règle l'intervalle de temps (en secondes) pendant lequel les icônes sont vérifiées pour être montrées/cachées, leur niveau alpha, les conditions, etc. Cela n'affecte pas les barres. Zéro : le plus rapide possible. De faibles valeurs peuvent avoir un impact important sur le nombre d'IPS pour des ordinateurs anciens."
L["UIPANEL_UPDATEINTERVAL"] = "Intervalle de mise à jour"
