--[[ Credit for these translations goes to:
	sunyruru
--]]
local L = LibStub("AceLocale-3.0"):NewLocale("TellMeWhen", "koKR", false)
if not L then return end








L["BleedDamageTaken"] = "출혈 공격받을 때"
L["Bleeding"] = "출혈 공격"
L["BonusAgiStr"] = "민첩/힘"
L["BonusArmor"] = "방어"
L["BonusMana"] = "마나"
L["BonusStamina"] = "스테미나"
L["BurstHaste"] = "영웅심/피의욕망"
L["BurstManaRegen"] = "마나 회복"
L["CHOOSENAME_DIALOG"] = [=[/ 버프가 / Debuff이 아이콘이 모니터에 원하는 이름이나 ID가 맞춤법 / 능력 / 항목의 입력하세요. 당신이 그들을 분리하여 여러 Buffs / Debuffs를 추가할 수 있습니다 ';'
애완 동물의 능력은 SpellIDs을 사용해야합니다.]=] -- Needs review
L["CHOOSENAME_DIALOG_DDDEFAULT"] = "미리 정의된 스킬/해제 세트"
L["CHOOSENAME_EQUIVS_TOOLTIP"] = "이 메뉴에 buffs / debuffs의 미리 정의된 집합을 선택할 수 있습니다." -- Needs review
L["CMD_OPTIONS"] = "옵션" -- Needs review
L["CONDITIONPANEL_AND"] = "및" -- Needs review
L["CONDITIONPANEL_ANDOR"] = "및 / 또는" -- Needs review
L["CONDITIONPANEL_ECLIPSE_DESC"] = "이클립스 -100 (달 일식은) 100의 범위를 가지고 (일식)  연구  nPercentages는 같은 방식으로 작동 :.  연구  nInput는 -80 당신은 80의 값을 작동하도록 아이콘을 원한다면 음력 전력. " -- Needs review
L["CONDITIONPANEL_EQUALS"] = "같음" -- Needs review
L["CONDITIONPANEL_GREATER"] = "초과" -- Needs review
L["CONDITIONPANEL_GREATEREQUAL"] = "이상 또는 동등 그레이터" -- Needs review
L["CONDITIONPANEL_LESS"] = "미만" -- Needs review
L["CONDITIONPANEL_LESSEQUAL"] = "이상 또는 동등 덜" -- Needs review
L["CONDITIONPANEL_NOTEQUAL"] = "같지 않음" -- Needs review
L["CONDITIONPANEL_OPERATOR"] = "연산자" -- Needs review
L["CONDITIONPANEL_OR"] = "또는" -- Needs review
L["CONDITIONPANEL_POWER_DESC"] = "단위는 고양이 형태의 사제는,  단위 등 전사하는 경우에는 연구  nrage 경우 에너지를 확인합니다" -- Needs review
L["CONDITIONPANEL_TITLE"] = "TellMeWhen 조건 편집기" -- Needs review
L["CONDITIONPANEL_TYPE"] = "종류" -- Needs review
L["CONDITIONPANEL_UNIT"] = "단위" -- Needs review
L["CONDITIONPANEL_VALUE"] = "퍼센트" -- Needs review
L["Disarmed"] = "방어무시"
L["Disoriented"] = "혼란"
L["ICONMENU_ABSENT"] = "없지만" -- Needs review
L["ICONMENU_ALPHA"] = "투명도"
L["ICONMENU_ALWAYS"] = "항상" -- Needs review
L["ICONMENU_BARS"] = "바" -- Needs review
L["ICONMENU_BUFF"] = "버프" -- Needs review
L["ICONMENU_BUFFDEBUFF"] = "버프/디버프"
L["ICONMENU_BUFFTYPE"] = "버프 또는 디버프?" -- Needs review
L["ICONMENU_CHOOSENAME"] = "스킬/아이템/버프/그외 선택"
L["ICONMENU_CLEAR"] = "초기화 설정"
L["ICONMENU_COOLDOWN"] = "쿨다운"
L["ICONMENU_COOLDOWNTYPE"] = "쿨다운 형식"
L["ICONMENU_DEBUFF"] = "디버프"
L["ICONMENU_EITHER"] = "모두"
L["ICONMENU_ENABLE"] = "아이콘 사용" -- Needs review
L["ICONMENU_FOCUSTARGET"] = "타겟 주시"
L["ICONMENU_FRIEND"] = "우호적"
L["ICONMENU_HOSTILE"] = "적대적"
L["ICONMENU_INVERTBARS"] = "바 채우기"
L["ICONMENU_ITEM"] = "항목"
L["ICONMENU_MANACHECK"] = "마나 체크?"
L["ICONMENU_ONLYMINE"] = "자신에게 시전 시에만 보이기"
L["ICONMENU_PETTARGET"] = "소환수의 타겟"
L["ICONMENU_PRESENT"] = "현재" -- Needs review
L["ICONMENU_RANGECHECK"] = "범위 확인?" -- Needs review
L["ICONMENU_REACT"] = "단위 반응" -- Needs review
L["ICONMENU_REACTIVE"] = "대응 조치 마법 또는 능력" -- Needs review
L["ICONMENU_SHOWCBAR"] = "쿨다운 / 타이머 바 보기"
L["ICONMENU_SHOWPBAR"] = "파워 바 보기"
L["ICONMENU_SHOWTIMER"] = "타이머 표시"
L["ICONMENU_SHOWWHEN"] = "아이콘 표시되면" -- Needs review
L["ICONMENU_SPELL"] = "스킬 또는 능력"
L["ICONMENU_STACKS_MAX_DESC"] = "아이콘을 표시하는 데 필요한 분위기의 스택의 최대수" -- Needs review
L["ICONMENU_STACKS_MIN_DESC"] = "아이콘을 표시하는 데 필요한 분위기의 스택의 최소 번호" -- Needs review
L["ICONMENU_TARGETTARGET"] = "대상의 대상"
L["ICONMENU_TOTEM"] = "/ 비 집고 양이인가 토템" -- Needs review
L["ICONMENU_TYPE"] = "아이콘 형식" -- Needs review
L["ICONMENU_UNUSABLE"] = "불가능" -- Needs review
L["ICONMENU_USABLE"] = "사용 가능" -- Needs review
L["ICONMENU_WPNENCHANT"] = "임시 무기 반갑습니다" -- Needs review
L["ICONMENU_WPNENCHANTTYPE"] = "무기 슬롯 모니터" -- Needs review
L["ICON_TOOLTIP1"] = "TellMeWhen"
L["ImmuneToMagicCC"] = "마법 면역"
L["ImmuneToStun"] = "스턴 면역"
L["Incapacitated"] = "움직이지 못함"
L["IncreasedAP"] = "공격력 증가"
L["IncreasedCrit"] = "치명타 / 극대화 확률 증가"
L["IncreasedDamage"] = "데미지 입힘"
L["IncreasedPhysHaste"] = "이동속도 증가"
L["IncreasedSPsix"] = "주문력 증가 (6%)"
L["IncreasedSPten"] = "주문력 증가 (10%)"
L["IncreasedSpellHaste"] = "주문가속 증가"
L["IncreasedStats"] = "능력치 증가"
L["ManaRegen"] = "마나 회복"
L["PhysicalDmgTaken"] = "물리 공격 받음"
L["PushbackResistance"] = "넉백 저항"
L["RESIZE"] = "크기 조정" -- Needs review
L["RESIZE_TOOLTIP"] = "클릭한 후 마우스를 끌어 크기를 조정"
L["ReducedArmor"] = "방어 감소"
L["ReducedAttackSpeed"] = "공격 속도 감소"
L["ReducedCastingSpeed"] = "주문시전 속도 감소"
L["ReducedHealing"] = "힐량 감소"
L["ReducedPhysicalDone"] = "물리 데미지 감소"
L["Resistances"] = "주문 저항"
L["Rooted"] = "루팅됨"
L["Silenced"] = "침묵됨"
L["UIPANEL_ALLRESET"] = "모두 초기화"
L["UIPANEL_BARTEXTURE"] = "바 텍스쳐" -- Needs review
L["UIPANEL_COLOR"] = "쿨다운/지속시간 바 색상"
L["UIPANEL_COLOR_COMPLETE"] = "쿨다운/지속시간 완료"
L["UIPANEL_COLOR_COMPLETE_DESC"] = "쿨다운/지속시간의 완료 시 바의 색상"
L["UIPANEL_COLOR_OOM"] = "마나 없음의 색상"
L["UIPANEL_COLOR_OOM_DESC"] = "농담 효과 그리고 당신은 마법을 행사할 / runicpower / 분노 / 초점 / 에너지 mana이 부족 아이콘 알파" -- Needs review
L["UIPANEL_COLOR_OOR"] = "범위 벗어남의 색상"
L["UIPANEL_COLOR_OOR_DESC"] = "농담 효과 및 아이콘의 알파 당신이 마법을 행사할 대상의 범위에 있지 않습니다" -- Needs review
L["UIPANEL_COLOR_STARTED"] = "쿨다운/지속시간 시작"
L["UIPANEL_COLOR_STARTED_DESC"] = "쿨다운/지속시간이 막 시작됨을 나타내는 바의 색상"
L["UIPANEL_COLUMNS"] = "항목" -- Needs review
L["UIPANEL_DRAWEDGE"] = "타이머 강조 테두리"
L["UIPANEL_DRAWEDGE_DESC"] = "쿨다운 타이머(시계 애니메이션)가 잘 보이도록 테두리를 강조합니다."
L["UIPANEL_ENABLEGROUP"] = "그룹 사용" -- Needs review
L["UIPANEL_GROUPRESET"] = "위치 초기화" -- Needs review
L["UIPANEL_ICONGROUP"] = "아이콘 그룹 " -- Needs review
L["UIPANEL_LOCK"] = "애드온 잠금"
L["UIPANEL_LOCKUNLOCK"] = "애드온 잠금/해제"
L["UIPANEL_MAINOPT"] = "주 옵션"
L["UIPANEL_ONLYINCOMBAT"] = "전투시에만 표시"
L["UIPANEL_PRIMARYSPEC"] = "기본 사양" -- Needs review
L["UIPANEL_ROWS"] = "행" -- Needs review
L["UIPANEL_SECONDARYSPEC"] = "보조 사양"
L["UIPANEL_STANCE"] = "보여지는 동안 :"
L["UIPANEL_SUBTEXT2"] = "은 아이콘이 잠겨 일할 때 잠금이 해제되면 / 크기 아이콘 그룹을 이동할 수있는 권리 기타 설정에 대한 개별 아이콘을 클릭하십시오 및 / 또는 잠금 해제 잠금 '/ tmw'을 입력할 수도 '/ tellmewhen'을하실 수 있습니다..." -- Needs review
L["UIPANEL_TOOLTIP_ALLRESET"] = "모든 아이콘 및 그룹의 위치와 데이터 초기화."
L["UIPANEL_TOOLTIP_COLUMNS"] = "그룹에 설정할 아이콘 열 수"
L["UIPANEL_TOOLTIP_ENABLEGROUP"] = "이 그룹을 보기 및 활성화"
L["UIPANEL_TOOLTIP_GROUPRESET"] = "그룹의 위치 재설정"
L["UIPANEL_TOOLTIP_ONLYINCOMBAT"] = "체크 시 전투 중에만 아이콘을 표시합니다."
L["UIPANEL_TOOLTIP_PRIMARYSPEC"] = "체크 시 기본 사양이 활성 상태일 때 이 그룹을 표시합니다"
L["UIPANEL_TOOLTIP_ROWS"] = "이 그룹의 행 수 설정"
L["UIPANEL_TOOLTIP_SECONDARYSPEC"] = "체크 시 이 그룹을 보조 사양이 활성 상태일 때 표시합니다"
L["UIPANEL_TOOLTIP_UPDATEINTERVAL"] = "세트 / 등은 지나칠 정도로 바에 영향을주지 않는다. 제로는 가능한 한 빨리하고, 알파, 조건을 숨길 수 있습니다. 로어 값은 로우 엔드에 대한 프레임 속도에 큰 영향을 미칠 수 컴퓨터 " -- Needs review
L["UIPANEL_UPDATEINTERVAL"] = "업데이트 간격" -- Needs review
