#!/bin/sh
#
# Copies the changelog to a format that can be loaded into WoW and displayed in-game

LAST_VERSION="5.0.2"
OUTPUT="Options/CHANGELOG.lua"
echo -e "if not TMW then return end\n\nTMW.CHANGELOG = {\n" > $OUTPUT;

while read line; do
	if [ "$line" == "===v$LAST_VERSION===" ]; then
		break;
	fi

	echo "[==[$line]==],";
done <CHANGELOG.txt >>$OUTPUT

echo "}" >> $OUTPUT;

echo "Wrote changelog up to $LAST_VERSION to $OUTPUT";

exit 0
