name: Package Retail/Wrath

on:
  push:
    branches:
      - master
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Validate Version"
        run: |
          if [[ "$(grep -hroP '## Version.*' --exclude-dir=.release --include="*.toc" . | sort --unique | wc -l)" -gt 1 ]]; then
            grep -rnP '## Version.*' --exclude-dir=.release --include="*.toc" . | cat
            echo "More than 1 distinct ##Version found in .toc files." 1>&2
            exit 1
          fi;

      - name: "Validate TOC Classic"
        run: |
          if [[ "$(grep -hroP '## X?-?\KInterface.*' --exclude-dir=.release --include="*-Classic.toc" . | sort --unique | wc -l)" -gt 1 ]]; then
            grep -rnP '## X?-?\KInterface.*' --exclude-dir=.release --include="*-Classic.toc" . | cat
            echo "More than 1 distinct ##Interface version found in .toc files." 1>&2
            exit 1
          fi;

      - name: "Validate TOC Wrath"
        run: |
          if [[ "$(grep -hroP '## X?-?\KInterface.*' --exclude-dir=.release --include="*-Wrath.toc" . | sort --unique | wc -l)" -gt 1 ]]; then
            grep -rnP '## X?-?\KInterface.*' --exclude-dir=.release --include="*-Wrath.toc" . | cat
            echo "More than 1 distinct ##Interface version found in .toc files." 1>&2
            exit 1
          fi;

      - name: "Validate TOC Retail"
        run: |
          if [[ "$(grep -hroP '## X?-?\KInterface.*' --exclude-dir=.release --include="TellMeWhen.toc" --include="TellMeWhen_Options.toc" . | sort --unique | wc -l)" -gt 1 ]]; then
            grep -rnP '## X?-?\KInterface.*' --exclude-dir=.release --include="TellMeWhen.toc" --include="TellMeWhen_Options.toc" . | cat
            echo "More than 1 distinct ##Interface version found in .toc files." 1>&2
            exit 1
          fi;
                
      - name: "Build In-Game Changelog"
        run: sudo chmod +x ./build/create-lua-changelog.sh && ./build/create-lua-changelog.sh
                
      - name: "Build Short Changelog"
        run: sudo chmod +x ./build/create-short-changelog.sh && ./build/create-short-changelog.sh
                
      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
