name: Package Classic

on:
  push:
    branches:
      - classic
    tags:
      - "*-classic"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: "Validate TOC"
        run: |
          if [[ "$(grep -hroP '## X?-?\KInterface.*' --exclude-dir=.release --include="*.toc" . | sort --unique | wc -l)" -gt 1 ]]; then
            grep -rnP '## X?-?\KInterface.*' --exclude-dir=.release --include="*.toc" . | cat
            echo "More than 1 distinct ##Interface version found in .toc files." 1>&2
            exit 1
          fi;
                
      - name: "Build In-Game Changelog"
        run: sudo chmod +x ./build/create-lua-changelog.sh && ./build/create-lua-changelog.sh
                
      - name: "Build Short Changelog"
        run: sudo chmod +x ./build/create-short-changelog.sh && ./build/create-short-changelog.sh
                
      - name: Create Package
        uses: BigWigsMods/packager@master
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}